- hosts: servers
  tasks:
    - git:
        repo: https://github.com/esma3el/migration_playground.git
        dest: "{{ dir_path }}"
        update: yes
    - command: docker compose -f {{ dir_path }}/compose.yaml up -d --build --force-recreate
  vars:
    ansible_ssh_user: "ismail"
    ansible_sudo_pass: "Supremk4!"
    dir_path: /home/ismail/migrate_play
