# Generated by Django 5.0.6 on 2024-06-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagemet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
