# Generated by Django 5.0.6 on 2024-06-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagemet', '0003_test_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
